### ISSUE TITLE
Support for Vaadin 8

### ISSUE THREAD

**Issue by maxschuster** [maxschuster/Vaadin-ColorPickerField#1]
Update this add-on to support vaadin 8

**Comment by atistrcsn** [comment]
Subscribe. I may help to migrate but I'm not so familiar with github+fork workflow :/

**Comment by maxschuster** [comment]
The ColorPicker of Vaadin 8 is a field (HasValue<Color>) now so you don't need this add-on anymore.

I ported the converters of this add-on for Vaadin 8: https://vaadin.com/directory#!addon/colorconverters

**Comment by atistrcsn** [comment]
Thanks for the useful info =)

Cheers.
